import { Opportunity } from './types';

export const MOCK_OPPORTUNITIES: Opportunity[] = [
  {
    id: 't3_4',
    title: 'Help! Need someone to assemble IKEA furniture ASAP!',
    subreddit: 'r/TwinCitiesSocial',
    author: 'u/furniture_fail',
    created_utc: Date.now() / 1000 - 600,
    permalink: 'https://www.reddit.com/r/TwinCitiesSocial/comments/4/',
    snippet: 'I bought a whole new bedroom set and I am completely lost with these instructions. SOS! Willing to pay well for quick help.',
    category: 'Odd Jobs',
    urgency: 'Immediate',
    budget: { min: 75, max: 150, type: 'fixed' },
    legitimacyScore: 88,
    skillMatch: 95,
  },
  {
    id: 't3_1',
    title: 'Looking for a reliable plumber for a leaky faucet in Uptown',
    subreddit: 'r/minneapolis',
    author: 'u/needs_a_plumber',
    created_utc: Date.now() / 1000 - 3600,
    permalink: 'https://www.reddit.com/r/minneapolis/comments/1/',
    snippet: 'My kitchen sink has been dripping for days and it\'s driving me crazy. Need someone who can come by this weekend. Any recommendations?',
    category: 'Home Repair',
    urgency: 'Within 24h',
    budget: { min: 50, max: 80, type: 'hourly' },
    legitimacyScore: 92,
    skillMatch: 90,
  },
  {
    id: 't3_2',
    title: 'Need a photographer for a family event in St. Paul next month',
    subreddit: 'r/saintpaul',
    author: 'u/family_guy_mn',
    created_utc: Date.now() / 1000 - 86400,
    permalink: 'https://www.reddit.com/r/saintpaul/comments/2/',
    snippet: 'We\'re having a small family reunion and want to capture the moments. Looking for someone with a good portfolio and reasonable rates.',
    category: 'Creative Services',
    urgency: 'Flexible',
    budget: { min: 400, max: 800, type: 'fixed' },
    legitimacyScore: 95,
    skillMatch: 75,
  },
    {
    id: 't3_6',
    title: 'Graphic Designer needed for a new coffee shop logo',
    subreddit: 'r/twincities',
    author: 'u/caffeine_dreamer',
    created_utc: Date.now() / 1000 - 250000,
    permalink: 'https://www.reddit.com/r/twincities/comments/6/',
    snippet: 'Opening a new cafe in the North Loop and need a cool, modern logo. Looking for someone with branding experience. Please send portfolios.',
    category: 'Creative Services',
    urgency: 'Flexible',
    legitimacyScore: 85,
    skillMatch: 85,
  },
  {
    id: 't3_3',
    title: 'Anyone know a good dog walker in the Edina area?',
    subreddit: 'r/twincities',
    author: 'u/dog_lover_88',
    created_utc: Date.now() / 1000 - 172800,
    permalink: 'https://www.reddit.com/r/twincities/comments/3/',
    snippet: 'I\'m starting a new job with longer hours and need someone to walk my golden retriever, Buster, on weekdays. Must be good with big dogs!',
    category: 'Pet Services',
    urgency: 'Ongoing',
    budget: { min: 20, max: 25, type: 'hourly' },
    legitimacyScore: 78,
    skillMatch: 60,
  },
  {
    id: 't3_5',
    title: 'Yard work help needed in Woodbury - leaves and gutters',
    subreddit: 'r/twincities',
    author: 'u/suburban_dad',
    created_utc: Date.now() / 1000 - 345600,
    permalink: 'https://www.reddit.com/r/twincities/comments/5/',
    snippet: 'The fall leaves have taken over my yard. Need someone to help with raking, bagging, and clearing out the gutters before winter hits.',
    category: 'Yard Work',
    urgency: 'Within 24h',
    budget: { min: 150, type: 'fixed' },
    legitimacyScore: 90,
    skillMatch: 80,
  },
];
